# Use Apache Derby file-based database
spring.datasource.url=jdbc:derby:${user.home}/.storrity/data/derby/storritydb;create=true
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Specify Hibernate dialect for Derby
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyTenSevenDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true