# Import external config if it exists
spring.config.import=optional:file:${user.home}/.storrity/conf/storrity.properties

## PostgreSQL Database Connection
#spring.datasource.url=${storrity_database}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=${storrity_user}
#spring.datasource.password=${storrity_pwd}
#
## JPA / Hibernate settings
##spring.jpa.hibernate.ddl-auto=create-drop
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=${storrity_ddl}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Optional: Log SQL statements
#spring.jpa.show-sql=true
#
## Disable H2 Console if no longer needed
#spring.h2.console.enabled=false

